### ISSUE TITLE
Repositories without .git suffix are ignored

### ISSUE THREAD

**Issue by jayvdb** [retr0h/git-url-parse#2]
`https://` URLs without `.git` are a `ParserError`.  GitHub and GitLab both support URLs without the `.git` (but GitLab emits a warning).

**Comment by retr0h** [comment]
I haven't found a case where github or gitlab will actually provide the user with a copy pastable URL that doesn't already contain `.git` in the URL.  How would one encounter a URL from these two sources w/o .git?

**Comment by rczajka** [comment]
Does this library actually only support parsing URLs provided by GitHub and GitLab? URLs without the `.git` suffix are valid git URLs.

**Comment by retr0h** [comment]
PRs always welcome.
