### ISSUE TITLE
git-url-parse took org name for repo name when given https://github.com/sphinx-doc/sphinx

### ISSUE THREAD

**Issue by chfw** [retr0h/git-url-parse#29]
```
>>> import giturlparse
>>> giturlparse.parse("https://github.com/sphinx-doc/sphinx.git")
Parsed(pathname='/sphinx-doc/sphinx.git', protocols=['https'], protocol='https', href='https://github.com/sphinx-doc/sphinx.git', resource='github.com', user=None, port=None, name='sphinx', owner='sphinx-doc')
>>> giturlparse.parse("https://github.com/sphinx-doc/sphinx")
Parsed(pathname='/sphinx-doc', protocols=['https'], protocol='https', href='https://github.com/sphinx-doc/sphinx', resource='github.com', user=None, port=None, name='sphinx-doc', owner=None)
```

Here is our issues:

https://github.com/moremoban/moban/issues/226

**Comment by retr0h** [comment]
@sks444 @jayvdb can you guys take a look at this since implemented as part of #4.

**Comment by retr0h** [comment]
![tenor-68203550](https://user-images.githubusercontent.com/9895/53992981-f80e8b00-40e2-11e9-9d78-651df31e3e5a.gif)

/cc @sks444 @jayvdb

**Comment by retr0h** [comment]
@chfw this was corrected, sorry it took so long.  I see you moved off my library already.  My apologies.

**Comment by chfw** [comment]
Thanks for the update. I can move back too. One thing I noticed is both library share the same module name space which makes library switching troublesome for user.

**Comment by retr0h** [comment]
@chfw Yeah, that's my bad.  I probably should have named it something else.

**Comment by chfw** [comment]
Would you like to update your module namespace? I think it is not that difficult to change.
